rootProject.name = "zipline-root"

include(":zipline")
include(":zipline-api-validator")
include(":zipline-cli")
include(":zipline-cryptography")
include(":zipline-gradle-plugin")
include(":zipline-bridge-annotations")
include(":zipline-bridge-kotlin-plugin")
include(":zipline-bridge-kotlin-plugin-tests")
include(":zipline-bridge-skew-old")
include(":zipline-bridge-skew-new")
include(":zipline-kotlin-plugin")
include(":zipline-kotlin-plugin-tests")
include(":zipline-loader")
include(":zipline-loader-testing")
include(":zipline-testing")
include(":intrinsic-tests")

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
