package app.cash.zipline.bridge.support

/**
 * Marker annotation for classes whose host-to-JS bridge code should be generated by the Zipline
 * bridge Kotlin compiler plugin.
 *
 * Classes annotated with this get a `convertToJs` method (JVM: an IR-injected external native
 * method implemented by generated C; Kotlin/Native: an IR-injected override of
 * [app.cash.zipline.Host2JsConvertible]) that builds a counterpart JS object in a QuickJS
 * context, recursively converting field values. Host objects of these classes can be pushed
 * into the guest as events.
 *
 * Note that this annotation is distinct from [WithJS2HostBridge], which generates the JS-to-host
 * direction. Classes that must round-trip in both directions carry both annotations.
 */
@Retention(AnnotationRetention.BINARY)
@Target(AnnotationTarget.CLASS)
public annotation class WithHost2JSBridge
